version: '3.9'

services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chuvandoan
      POSTGRES_DB: student_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: ./api
    container_name: api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:chuvandoan@db:5432/student_db
    ports:
      - "3000:8000"

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - api
    ports:
      - "80:3000"

volumes:
  db_data:
